version: '3.7'

services: 

    backend:
        image: oneeleven
        build: ../../part1/1.11
        volumes: 
            - ./lelogs.txt:/backend/logs.txt
        ports: 
            -  8000:8000
        environment: 
            - REDIS=red
            - REDIS_PORT=6379
        depends_on: 
            - red
    frontend:
        image: oneten
        build: ../../part1/1.10
        ports: 
            - 5000:5000
        depends_on:
            - "backend"
    red:
        image: "redis"
