version: '3.7'

services: 

    backend:
        image: oneeleven
        build: ../../part1/1.11
        volumes: 
            - ./lelogs.txt:/backend/logs.txt
        ports: 
            -  8000:8000
        environment: 
            - REDIS=red
            - REDIS_PORT=6379
            - DB_USERNAME=user
            - DB_PASSWORD=password
            - DB_NAME=postgres
            - DB_HOST=db
        depends_on: 
            - red
            - db
    frontend:
        image: oneten
        build: ../../part1/1.10
        ports: 
            - 5000:5000
        depends_on:
            - "backend"
    red:
        image: "redis"
        restart: unless-stopped
    db:
        image: postgres
        restart: unless-stopped
        environment: 
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=postgres
